import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidedrawer from '../components/sidedrawer'
import { useState } from 'react'
import UrlWrapper from '../components/urlWrapper'
import PlayerWrapper from '../components/playerWrapper'

export default function Home() {

  const [show, setShow] = useState(false);

  const [urlList, setUrlList] = useState<string[]>(["https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8"]);

  return (
    <div className="container text-sky-400">
      <Head>
        <title>Multi HLS Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-slate-700'>
        Multi HLS Player
      </h1>

      <main className="container">
        <button 
          className="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg  focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out mr-1.5" 
          type="button" 
          onClick={() => setShow(true)}
        > 
        Control 
        </button>

        <Sidedrawer show={show} setShow={setShow} urlList={urlList} setUrlList={setUrlList}>
          {urlList.map((url, index) => {
            return(
              <UrlWrapper url={url} key={index} urlList={urlList} setUrlList={setUrlList}/>
            )
          })}
        </Sidedrawer>

        {urlList.map((url, index) => {
          return(
            <PlayerWrapper url={url} key={index} />
          )
        })}

        <h1 className="text-3xl">Now Playing</h1>

        
      </main>

      <footer className=''>
        <a>
          Contact me 
        </a>
      </footer>
    </div>
  )
}
