import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Sidedrawer from '../components/sidedrawer'
import { useState } from 'react'
import UrlWrapper from '../components/urlWrapper'
import PlayerWrapper from '../components/playerWrapper'
import { useAppDispatch } from '../redux/store'
import { useSelector } from 'react-redux'
import { addUrl, deleteUrl, editUrl, UrlType } from '../redux/slice/url'
import { RootState } from '../redux/reducer'
import { url } from 'inspector'

export default function Home() {

  const [show, setShow] = useState(false);

  const urlList = useSelector((state: RootState) => state.url.urlList);
  
  const playerMapper = urlList.map((url: UrlType) => {
    return(
      <PlayerWrapper url={url.url} key={url.id} id={url.id} />
    )
  })  

  return (
    <div className="container text-sky-400">
      <Head>
        <title>Multi HLS Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-slate-700 text-lg'>
        Multi HLS Player
      </h1>

      <main className="container">
        <button 
          className="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg  focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out mr-1.5" 
          type="button" 
          onClick={() => setShow(true)}
        > 
        Control 
        </button>

        <Sidedrawer show={show} setShow={setShow} />

        <div className="flex flex-wrap">
          {playerMapper}
        </div>
      </main>

      <footer className='text-black'>
        Contact me: 
        <br/>
        <a className='text-red' href='tx0203@gmail.com'>
          tx0203@gmail.com  
        </a>
      </footer>
    </div>
  )
}
