import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import Sidedrawer from '../components/sidedrawer'
import { useState } from 'react'

const DynamicPlayer = dynamic(() => import('../components/player'), {
  ssr: false,
})

export default function Home() {

  const [show, setShow] = useState(false);

  return (
    <div className="container text-sky-400">
      <Head>
        <title>Multi HLS Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">

        <div className='text-sky-400 bg-red-100 w-full flex justify-center'>Tailwind Test</div>
        <h1 className="text-3xl">Now Playing</h1>
        <DynamicPlayer url="https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8" />
        <DynamicPlayer url="https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8" />
        <DynamicPlayer url="https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8" />

        <button 
          className="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg  focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out mr-1.5" 
          type="button" 
          onClick={() => setShow(true)}
        > 
        Control 
        </button>

        <Sidedrawer show={show} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
